name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
    # docker build . --file Dockerfile --tag my-image-name:$IMAGE_TAG
      run: |
        echo $GITHUB_ENV
        export IMAGE_TAG = "$GITHUB_RUN_ID$(date '+%H%M%S')-$GITHUB_REF_NAME"
        echo $IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
    - name: Testing persisted variables
      run: |
        echo $GITHUB_ENV
        echo $IMAGE_TAG
    # - name: Run Trivy vulnerability scanner
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
    #     format: 'table'
    #     exit-code: '1'
    #     ignore-unfixed: true
    #     vuln-type: 'os,library'
    #     severity: 'CRITICAL,HIGH'