name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        export NEWVAR=valor1
        export DB_HOST="asdasdasa"
        echo $NEWVAR
        echo $DB_HOST
        echo $GITHUB_RUN_ID
        echo $GITHUB_RUN_NUMBER
        echo $GITHUB_REF
        echo $GITHUB_REF_NAME
        pwd
        echo "testandoarquivo" > file.txt
        ls
        cat file.txt
    - name: Test if values are persisted across steps
      run: |
        pwd
        ls
        cat file.txt
        echo $NEWVAR
        echo $DB_HOST
        docker image ls
        echo $GITHUB_RUN_ID