name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        export IMAGE_TAG="$GITHUB_RUN_ID$(date '+%H%M%S')-$GITHUB_REF_NAME"
        docker build . --file Dockerfile --tag ${{ secrets.IMAGE_NAME }}:$IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.IMAGE_NAME }}:$IMAGE_TAG
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH,MEDIUM,LOW,INFO'